# Conclusion

The data on new and existing business licenses highlight the severe impact of the pandemic in the city. The data on approved licenses for new businesses display seasonal fluctuation. Looking through seasonal variation, they declined substantially across the five boroughs of the city due to the raging pandemic. The data on currently operating business licenses also show a notable drop-off in 2020 through 2021. While most regions showed some recovery since the onset of the pandemic, the recovery in some neighborhoods is slower than in other areas. Interestingly, the areas that showed a stronger rebound in new business license applications are neighborhoods that are father in the outer-boroughs, which tend to display higher poverty rates, lower educational attainment rates, and less widespread access to high-speed internet. This is possibly due to an abrupt shift in lifestyle with more prevalent remote work. Still, many office workers in the city's commercial neighborhoods have yet to return, implying a slower recovery in these areas. 

The limitation of this exercise is that the datasets from the NYC Department of Consumer Affairs lack where these new and existing businesses are located, which makes it difficult to verify what the data seem to indicate in real life. The numbers we used for our analyses only include the businesses with NYC mailing addresses. Since there could be many businesses still operating in NYC while having non-NYC mailing addresses, our analyses could be underestimating the impact of the pandemic as well as the ensuing recovery. Moreover, there could be some cases in which the business owner's licenses are considered active in our operating business dataset although the business has already closed as administrative data tend to get updated with a lag.

There are certainly other alternative sources of information that can enrich our analysis further. Google's [Community Mobility Report](https://www.google.com/covid19/mobility/), for example, measures resident mobility by venue type (e.g., offices vs. recreational services), based on user location data. This additional information could add another dimension to analyzing the impact of the pandemic. 
